CLASS32-DEVOPS-cloud/student-profiles-review

index.html
Added new review for libertyc31
=> added profile for libertyc31

index.html
modified index.html to include review for new student Racheal Ariweriokuma
=> add review for Racheal Ariweriokuma

index.html
=> liontech05

index.html
I modified file index.html to include review for current student Eric
=> added review for Eric

index.html
Added a new review for Etini Patrick
=> Added profile for Etini Patrick

index.html
=> added profile for Yimbuh

index.html
I did updated the index. html to include manuel Nk
=> Profile updated-Manuel

index.html
Added a new review for Marcel KOFFI
=> added new profile for Marcel_koffi

index.html
Modified index.html file to include Sample Profile for Chiemezie
=> added Sample Profile of Chiemezie

index.html
=> I have added my profile review Adu Oluwaseun

index.html
=> i did a find and replace option -libertyc31 to Fai

index.html
=> added profile samuel

index.html
=> Denis profile added

index.html
corrected some errors on my profile
=> made some corrections on my profile

index.html
=> some few more errors corrected

index.html
modified index.html to include review for oghogho o
=> added a review for OGHOGHO O

index.html
corrected some mistakes in chimezie's profile
=> corrected some error in chimezie's j profiles

index.html
Salami renamed my first job.
Created a new sample again.
=> added new sample profile for PJAY

index.html
=> added profile for Modest K

index.html
Added a new review for Marcel Koffi
=> added profile for Marcel Koffi

index.html
Phanuel Changed the color of the rating
=> Phanuel added Profile update
